# Generated by Django 4.0.4 on 2022-06-26 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_developer_game_gamegenre_gamemode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('Verified', models.BooleanField(default=False)),
                ('specialisation', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('Verified', models.BooleanField(default=False)),
                ('amount_of_films', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieSeriesGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_of_release', models.DateField()),
                ('Verified', models.BooleanField(default=False)),
                ('summary', models.TextField(default='summary', max_length=1000)),
                ('number_of_seasons', models.CharField(max_length=100)),
                ('actors', models.ManyToManyField(to='polls.actor')),
                ('director', models.ManyToManyField(to='polls.director')),
                ('genre', models.ManyToManyField(to='polls.movieseriesgenre')),
                ('language', models.ManyToManyField(to='polls.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url', models.TextField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_description', models.TextField(blank=True, max_length=100, null=True)),
                ('signature', models.TextField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Undefined')], default='u', help_text='What is your gender', max_length=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_of_release', models.DateField()),
                ('Verified', models.BooleanField(default=False)),
                ('summary', models.TextField(default='summary', max_length=1000)),
                ('running_time', models.CharField(max_length=100)),
                ('actors', models.ManyToManyField(to='polls.actor')),
                ('director', models.ManyToManyField(to='polls.director')),
                ('genre', models.ManyToManyField(to='polls.movieseriesgenre')),
                ('language', models.ManyToManyField(to='polls.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
